name: ticket_app
description: Basic Flutter app with 3 pages and bottom navigation.
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_slidable: ^3.0.1
  image_picker: ^1.1.2
  http: ^1.2.2
  supabase_flutter: ^2.5.6
  mobile_scanner: ^5.2.3  # QR/Barcode scanner
  image: ^4.2.0
  currency_picker: ^2.0.19
  shared_preferences: ^2.3.2
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  fl_chart: ^0.69.0  # Интерактивные графики для аналитики
  intl: any  # Форматирование дат (из flutter_localizations)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner: ^2.4.13
  riverpod_generator: ^2.4.0
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  generate: true


